users: 
  documentId: userID
  name: String
  iconULR: String?
  profile: String?
  cratedAt: Date

products:
  documentId: String
  title: String
  userName: String
  sorceCode: String
  tagsIDs: [String]
  likes: Number
  open: boolean
  comments:
    documentId: auto
    comment: String
  createdAt: Date

tags:
  documentId: String
  name: String
  createdAt: Date
  count: Number
