users: 
  documentId: userID
  name: String
  iconULR: String?
  profile: String?
  cratedAt: Date

products:
  documentId: String
  title: String
  content: String
  userId: String
  sorceCode: String
  tagsIDs: [String]
  likes: Number
  open: boolean (公開OR非公開)
  comments:
    documentId: auto
    comment: String
  createdAt: Date

tags:
  documentId: String
  createdAt: Date
  count: Number
